steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - Dockerfile.api
      - -t
      - gcr.io/dacora---tarefas/taskora-api:latest
      - .
images:
  - gcr.io/dacora---tarefas/taskora-api:latest
